### PR TITLE
Add Go Mono

### PR DESCRIPTION
**Pull request by herrbischoff**
Font for the Go programming language. For more details, please see: https://blog.golang.org/go-fonts

### CODE REVIEW

**Comment by andreastt** [comment]
I was about to open a PR to add the Go Mono font, but found this.

It doesn’t appear that this adds the font sources as embedded Base64 strings. This means that the fonts must be available on the local system for this change to work. Is this intentional due to some licensning situation?

**Comment by herrbischoff** [comment]
I don't understand what you mean. They are indeed embedded base64 strings. The diffs are too large for GitHub to display them via web interface. Also, they work. I'm using Blink with Go Mono right now, no locally installed typeface.

**Comment by andreastt** [comment]
Sorry for the false report! It looks like I ran into a browser bug, where `src: url(…)` isn’t rendered:

Screenshot 2020-10-30 at 09 25 21

The [raw diff](https://patch-diff.githubusercontent.com/raw/blinksh/fonts/pull/19.diff) looks absolutely fine.

@yury Any chance this could be merged in?

**Comment by yury** [comment]
Thanks for heads up!

**Pull request merged**
