### PR TITLE
Updated Fira Code Nerd Font URL

### PR DESCRIPTION
**Pull request by thegcat**
The files are called `Fira` now and not `Fura` anymore.

### CODE REVIEW

**Comment by assistcontrol** [comment]
Can somebody please merge this? This is a very popular font, it’s a simple fix, and it’s been waiting 1.5 years. It would be nice to have this in the app without having to use a personal gist to work around it.

**Comment by taniki** [comment]
import the PR file if you don't have hope about this being merge

URL : `https://raw.githubusercontent.com/blinksh/fonts/b3dc494c6a1458d64883b1932c1c97adfd8fc09d/Fira%20Code%20Nerd%20Font.css`

**Comment by dRaiser** [comment]
> import the PR file if you don't have hope about this being merged anytime soon.
> 
> URL : `https://raw.githubusercontent.com/blinksh/fonts/b3dc494c6a1458d64883b1932c1c97adfd8fc09d/Fira%20Code%20Nerd%20Font.css`

Thank you so much @taniki ! Spent way too many hours trying to find fix for broken nerd fonts in Blink.sh and this is finally good solution.

**Comment by trolley** [comment]
@carloscabanero Could this get merged?

**Comment by carloscabanero** [comment]
Yep, will do another pass to update all of them. Looks like we are a bit behind

**Pull request merged**
