### PR TITLE
Add Nerd Font variant of Fira Code

### PR DESCRIPTION
**Pull request by malob**

### CODE REVIEW

**Comment by malob** [comment]
Oops, missed that there was already another full request :p

**Comment by malob** [comment]
Look, like other PR for same font was closed by owner, so reopening.

**Comment by malob** [comment]
@yury, is anyone looking at PRs in this repository?

The readme encourages people to submit PRs, but they don't seem to be getting any attention:

> We know how important it is for you to have your color scheme and the font that you feel comfortable looking at all day. And don't forget to send us your PR to share them with others too!

**Comment by yury** [comment]
Oh, sorry, missed that. Thank you for heads up. Watching this repo now.

**Comment by malob** [comment]
Thanks so much for the quick response!

**Pull request merged**
